services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama

  chromadb:
    image: chromadb/chroma:0.5.6.dev71
    container_name: chromadb
    ports:
      - '8000:8000'
    volumes:
      - ./chromadb:/chroma/data # Bind mount not a named volume
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/data # Default folder where chroma stores data
      - ANONYMIZED_TELEMETRY=FALSE
  
  spring-boot:
    build:
      context: './Spring RAG'
      dockerfile: Dockerfile
    container_name: spring-boot
    ports:
      - '8080:8080'
    volumes:
      - './Spring RAG/src:/app/src' # TODO: REMOVE AFTER FINISHED
      - './Spring RAG/knowledge_base:/app/knowledge_base' # This is going to copy all the files into the container

volumes:
  ollama:
