services:
  ollama:
    image: 'ollama/ollama:latest'
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector
    environment:
      - 'POSTGRES_DB=rag'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  ollama:
  postgres_data: